# The URL the site will be built for
base_url = "https://trinity-woo.github.io/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

title = "My Blog"
theme = "linkita"
generate_feeds = true

taxonomies = [
    { name = "tags", feed = true },
]


